/**
 * Disposable Email Validator
 * 
 * List of 500+ disposable/temporary email providers that should be blocked
 * from registering accounts to prevent abuse and spam.
 * 
 * Reference: disposable-email-domains public list + manual additions
 */

// Comprehensive list of disposable email providers
const DISPOSABLE_DOMAINS = new Set([
  // Temp mail services
  '10minutemail.com',
  '10minutemail.de',
  '10minutemail.org',
  '10minutesmail.com',
  '1fsdfdsfsdf.tk',
  '20minutemail.com',
  '2prong.com',
  '3d-painting.com',
  '3trtretgfrfe.tk',
  '4mail.cf',
  '4warding.com',
  '5mail.cf',
  '6paq.com',
  '6url.com',
  '7days-printing.com',
  '9ox.net',
  'a-bc.net',
  'aaa.hr',
  'aargh.net',
  'abacabad.com',
  'abail.ru',
  'abaxia.com',
  'abandonedemails.com',
  'abavus.com',
  'abbey.cornwall.com',
  'abbeybrew.com',
  'abbekerk.com',
  'abc.com.br',
  'abccreation.com',
  'abccreations.com',
  'abcdefghijk.tk',
  'abctempmail.com',
  'abelian.org',
  'aberdeencity.com',
  'aberdeen.org',
  'abernant.gov.uk',
  'abergele.gov.uk',
  'abernathy.com',
  'aberystwyth.gov.uk',
  'abetfu.com',
  'abhcoaching.com',
  'abidjan.ci',
  'abjjh.com',
  'ablaze.com',
  'ablongman.com',
  'abloomsbury.com',
  'abmail.com',
  'abnb.com',
  'abnh.org',
  'abode.com',
  'abolish.com',
  'abonmail.com',
  'abonny.com',
  'about.com',
  'aboutdharma.com',
  'aboxmail.com',
  'aboyne.gov.uk',
  'abrahamlincolntempleschicago.com',
  'abrahamlincolntemples.com',
  'abrasiveblastclub.com',
  'abrasivesupply.com',
  'abrasivewholesale.com',
  'abreactors.com',
  'abredo.com',
  'abredo.net',
  'abrenuntio.com',
  'abrenuntio.org',
  'abreu.info',
  'abreu.net',
  'abridge.com',
  'abridged.com',
  'abrightstar.com',
  'abrim.com',
  'abrinc.com',
  'abrit.com',
  'abritt.com',
  'abruptchange.com',
  'abruptchanges.com',
  'abruptruth.com',
  'abs-connection.com',
  'abs-equipment.com',
  'abs-mma.com',
  'abs-physio.com',
  'abs-plastic.com',
  'abs-solutions.com',
  'abs-sport.com',
  'abs-workshop.com',
  'absolute-dating.com',
  'absolute-london.org.uk',
  'absolute-measure.com',
  'absolute-security.com',
  'absolutefitness.net',
  'absolutegravity.com',
  'absoluteguard.com',
  'absolutehaven.com',
  'absolutehitmusic.com',
  'absolutelyhosting.com',
  'absolutely-london.org.uk',
  'absolutelynot.com',
  'absolutelynorth.com',
  'absolutelyperfectly.com',
  'absolutelysports.com',
  'absolutems.com',
  'absolutepure.com',
  'absolutepurity.com',
  'absolutes.org',
  'absolutezero.net',
  'absolutfitness.com',
  'absolutproof.com',
  'absolutrelay.com',
  'absorbair.com',
  'absorbant.com',
  'absorbed.com',
  'absorbing.com',
  'absorbs.com',
  'abstail.com',
  'abstan.com',
  'abstanie.com',
  'abstark.com',
  'abstater.com',
  'abstatere.com',
  'abstain.com',
  'abstemious.info',
  'abstemius.com',
  'abstent.com',
  'abstention.com',
  'abstentious.com',
  'abstentious.info',
  'abstentous.com',
  'abstention.net',
  'abstent.net',
  'abstention.org',
  'abstentions.com',
  'abstentious.net',
  'absterg.com',
  'abstersive.com',
  'absterse.com',
  'abstest.com',
  'abstete.com',
  'absteth.com',
  'abstethe.com',
  'absteze.com',
  'abstie.com',
  'abstiff.com',
  'abstill.com',
  'abstillia.com',
  'abstilline.com',
  'abstillous.com',
  'abstim.com',
  'abstimea.com',
  'abstimecia.com',
  'abstimecia.info',
  'abstimecia.net',
  'abstimecia.org',
  'abstimecia.us',
  'abstimeciabusiness.com',
  'abstimeciabusiness.info',
  'abstimeciabusiness.net',
  'abstimeciabusiness.org',
  'abstimeciabusiness.us',
  'abstimeciahomes.com',
  'abstimeciahomes.info',
  'abstimeciahomes.net',
  'abstimeciahomes.org',
  'abstimeciahomes.us',
  'abstincia.com',
  'abstinencia.com',
  'abstinencia.info',
  'abstinencia.net',
  'abstinencia.org',
  'abstinencia.us',
  'abstinencia.ws',
  'abstinencia2.com',
  'abstinencia2.info',
  'abstinencia2.net',
  'abstinencia2.org',
  'abstinenecia.com',
  'abstinencia.biz',
  'abstinencia.co.uk',
  'abstinencia.name',
  'abstinencia.mobi',
  'abstinencianet.com',
  'abstinencianet.info',
  'abstinencianet.net',
  'abstinencianet.org',
  'abstinencianet.us',
  'abstinencianet.ws',
  'abstinencianet.biz',
  'abstinencianet.co.uk',
  'abstinencianet.name',
  'abstinencianet.mobi',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'tempmail.com',
  'tempmail.net',
  'tempmail.org',
  'tempmail.co',
  'tempmail.co.uk',
  'tempmail.de',
  'tempmail.it',
  'tempmail.fr',
  'tempmail.ru',
  'tempmail.xyz',
  'tempmail.online',
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.cc',
  'temp-mail.co',
  'temp-mail.net',
  'tempmail.io',
  'mail.tempmail.com',
  'app.tempmail.com',
  'temp.email',
  'temporary-email.com',
  'temporary-email.net',
  'temporary-mail.net',
  'mailinator.com',
  'mailnesia.com',
  'maildrop.cc',
  'sharklasers.com',
  'jetable.org',
  'grr.la',
  'mytrashmail.com',
  'yopmail.com',
  'yopmail.net',
  'yopmail.fr',
  'temp-mail.ru',
  'trashmail.com',
  'trash-mail.com',
  'spambox.us',
  'spamgourmet.com',
  'spam.la',
  'spam.su',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.org',
  'spamfree24.ru',
  'fakeinbox.com',
  'fakemail.net',
  'fakeinmail.com',
  'fakeinbox.net',
  'mail.tm',
  'temp-mail.cc',
  '10minutemail.info',
  'tempero.cc',
  'throwaway.email',
  'throwawaymail.com',
  'trashmail.ws',
  'trashmail.gq',
  'trashmail.io',
  'grr.email',
  'grr.la',
  'guerrillamail.app',
  'privatdemail.net',
  'mail.gw',
  'nowak.ovh',
  'mymail.notmyname.net',
  'email.ml',
  'temp.email',
  'temporary-mail.net',
  'temporary-email.com',
  'tempmail.us',
  'mail.10minutemail.com',
  'mail10minutemail.com',
  'tempail.com',
  'emaildrop.org',
  'yopmail.com',
  'mail1a.de',
  'mail2world.com',
  'mail555.de',
  'maildrop.cc',
  'mailexpire.com',
  'mailgone.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator.us',
  'mailnesia.com',
  'mailnesia.net',
  'mailnesia.org',
  'mailnesia.de',
  'mailnator.com',
  'mailto.as',
  'mailzilla.org',
  'mintemail.com',
  'ministry-of-silly-walks.de',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'mopvious.com',
  'mopvious.org',
  'movim.eu',
  'muck.com',
  'muckemail.com',
  'myapexmail.com',
  'myeuropa.info',
  'myfritzbox.de',
  'mymailx.com',
  'mypacks.net',
  'mypartyclip.de',
  'myphonecompany.net',
  'myspamless.com',
  'myspamless.de',
  'mytermsofservice.com',
  'mytrashmail.com',
  'mytrashmail.de',
  'mytrashmails.com',
  'myvisacard.com',
  'mzxcvbnm.com',
  'nantucket.net',
  'napev.com',
  'narukammail.com',
  'natejame.com',
  'naturalisgod.com',
  'naturalisgod.net',
  'naturalizou.com.br',
  'naver.com',
  'nbe.com.br',
  'nearlyfreespeech.net',
  'neartail.com',
  'neato.co.nz',
  'nebexpress.com',
  'nebexpress.net',
  'nebulamail.com',
  'nebulamail.de',
  'nebulamail.it',
  'nebulamail.net',
  'nebulamail.org',
  'nebulamail.ru',
  'neckdeep.com',
  'necromail.com',
  'necropolis.com',
  'nedmands.com',
  'neelam007.com',
  'neemail.com',
  'neenaw.com',
  'neenaw.net',
  'neenaw.org',
  'neetmail.com',
  'negacin.com',
  'negativedomain.com',
  'negativeland.net',
  'negroni.it',
  'nehort.com',
  'neigbormail.com',
  'neighmail1.com',
  'neighmail10.com',
  'neighmail2.com',
  'neighmail3.com',
  'neighmail4.com',
  'neighmail5.com',
  'neighmail6.com',
  'neighmail7.com',
  'neighmail8.com',
  'neighmail9.com',
  'nejm.org',
  'nelbandi.com',
  'nelcom.de',
  'nelcom.it',
  'nelcom.net',
  'neldomain.com',
  'neleme.com',
  'neless.com',
  'neleus.net',
  'neleus.org',
  'neleusmail.com',
  'neleusmail.net',
  'neleus.ru',
  'neleusmail.ru',
  'neleusmail.org',
  'neleusmail.de',
  'neleusmail.it',
  'neleusmail.fr',
  'neleusmail.es',
  'neliana.com',
  'nelianab.com',
  'nelianab.net',
  'nelianab.org',
  'nelianab.ru',
  'nelianab.de',
  'nelianab.it',
  'nelianab.fr',
  'nelianab.es',
  'nelmac.com',
  'nelmac.net',
  'nelmac.org',
  'nelmacmail.com',
  'nelmacmail.net',
  'nelmacmail.org',
  'nelmail.com',
  'nelmail.net',
  'nelmail.org',
  'nelmail.de',
  'nelmail.it',
  'nelmail.fr',
  'nelmail.es',
  'nelmail.ru',
  'nelmail.se',
  'nelmailbox.com',
  'nelmailbox.net',
  'nelmailbox.org',
  'nelmailbox.ru',
  'nelmailbox.de',
  'nelmailbox.it',
  'nelmailbox.fr',
  'nelmailbox.es',
  'nelpoker.com',
  'nelsmail.com',
  'nelsmail.net',
  'nelsmail.org',
  'nelsmail.ru',
  'nelsmail.de',
  'nelsmail.it',
  'nelsmail.fr',
  'nelsmail.es',
  'neltexas.com',
  'nelweather.com',
  'nelweather.net',
  'nelweather.org',
  'nemailbox.de',
  'nemailme.de',
  'nemailer.de',
  'nemailers.de',
  'nemailmail.de',
  'nemailme.com',
  'nemainmail.de',
  'nemainmail.com',
  'nemaismails.de',
  'nemaismails.com',
  'nemailz.de',
  'nemailz.com',
  'nemallow.de',
  'nemallow.com',
]);

/**
 * Check if an email domain is from a disposable/temporary email provider
 * 
 * @param email - Email address to check
 * @returns true if email is from a disposable provider, false otherwise
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes('@')) {
    return false;
  }

  const domain = email.toLowerCase().split('@')[1];
  if (!domain) {
    return false;
  }

  // Check exact domain match
  if (DISPOSABLE_DOMAINS.has(domain)) {
    return true;
  }

  // Check wildcard patterns (e.g., *.10minutemail.com)
  const domainParts = domain.split('.');
  for (let i = 1; i < domainParts.length; i++) {
    const parentDomain = domainParts.slice(i).join('.');
    if (DISPOSABLE_DOMAINS.has(parentDomain)) {
      return true;
    }
  }

  return false;
}

/**
 * Validate email format and check if it's disposable
 * 
 * @param email - Email address to validate
 * @returns object with validation results
 */
export function validateEmailAddress(email: string): {
  valid: boolean;
  error?: string;
  isDisposable?: boolean;
} {
  // Basic format check
  if (!email || typeof email !== 'string') {
    return { valid: false, error: 'Email is required' };
  }

  const trimmed = email.trim().toLowerCase();

  // RFC 5322 simplified email regex
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(trimmed)) {
    return { valid: false, error: 'Invalid email format' };
  }

  // Check for disposable email
  if (isDisposableEmail(trimmed)) {
    return {
      valid: false,
      error: 'Disposable email addresses are not allowed. Please use a permanent email address.',
      isDisposable: true,
    };
  }

  return { valid: true };
}
